#!/bin/zsh
set -euo pipefail

DOMAINS="${1:-$HOME/Downloads/cn-domains-for-local-dns.txt}"
DNS1="${2:-223.5.5.5}"
DNS2="${3:-119.29.29.29}"
RESOLVER_DIR="/etc/resolver"
MARKER="tailGateway-dns-split"

as_root() {
  if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

[[ -f "$DOMAINS" ]] || { echo "Missing domain list: $DOMAINS" >&2; exit 1; }
[[ "$DNS1" =~ '^[0-9]+(\.[0-9]+){3}$' ]] || { echo "Invalid DNS1: $DNS1" >&2; exit 1; }
[[ "$DNS2" =~ '^[0-9]+(\.[0-9]+){3}$' ]] || { echo "Invalid DNS2: $DNS2" >&2; exit 1; }

as_root mkdir -p "$RESOLVER_DIR"

count=0
while IFS= read -r suffix; do
  suffix="${suffix%%#*}"
  suffix="${suffix#"${suffix%%[![:space:]]*}"}"
  suffix="${suffix%"${suffix##*[![:space:]]}"}"
  [[ -z "$suffix" ]] && continue

  safe="${suffix//\\//}"
  [[ "$safe" == "$suffix" ]] || continue

  tmp="$(mktemp)"
  {
    echo "# $MARKER"
    echo "# Generated by TailGateway"
    echo "nameserver $DNS1"
    echo "nameserver $DNS2"
    echo "port 53"
    echo "timeout 2"
    echo "search_order 1"
  } > "$tmp"
  as_root install -m 0644 "$tmp" "$RESOLVER_DIR/$suffix"
  rm -f "$tmp"
  count=$((count + 1))
done < "$DOMAINS"

dscacheutil -flushcache >/dev/null 2>&1 || true
as_root killall -HUP mDNSResponder >/dev/null 2>&1 || true

echo "Installed $count TailGateway DNS split resolver files in $RESOLVER_DIR."
echo "DNS: $DNS1, $DNS2"
